version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    container_name: odoo18
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - odoo18-web-data:/var/lib/odoo
    command: odoo -c /etc/odoo/odoo.conf

volumes:
  odoo18-db-data:
  odoo18-web-data:
